create unique index IDX_ASSISTANCE_COUNTRY_UK_ALPHA2 on ASSISTANCE_COUNTRY (ALPHA2) ;
create unique index IDX_ASSISTANCE_COUNTRY_UK_NAME_EN on ASSISTANCE_COUNTRY (NAME_EN) ;
create unique index IDX_ASSISTANCE_COUNTRY_UK_NAME on ASSISTANCE_COUNTRY (NAME) ;
create unique index IDX_ASSISTANCE_COUNTRY_UK_ALPHA3 on ASSISTANCE_COUNTRY (ALPHA3) ;
