alter table ASSISTANCE_DISTRICT add constraint FK_ASSISTANCE_DISTRICT_ON_REGION foreign key (REGION_ID) references ASSISTANCE_REGION(ID);
create index IDX_ASSISTANCE_DISTRICT_ON_REGION on ASSISTANCE_DISTRICT (REGION_ID);
