alter table ASSISTANCE_SUB_PRODUCT add constraint FK_ASSISTANCE_SUB_PRODUCT_ON_PRODUCT foreign key (PRODUCT_ID) references ASSISTANCE_PRODUCT(ID);
create index IDX_ASSISTANCE_SUB_PRODUCT_ON_PRODUCT on ASSISTANCE_SUB_PRODUCT (PRODUCT_ID);
